### PR TITLE
Adding a Onboarding Screen for new users and new updates.

### PR DESCRIPTION
**Pull request by rajhraval1**
I tried to achieve the feature, mentioned in #25 

Onboarding is shown only once when the app is installed for the first time or has got a new update.
I have also added an Image, when there are no quotes (Footnotes) added.

| Onboarding Screen - Light Mode | Empty Quotes State - Light Mode | Onboarding Screen- Dark Mode | Empty Quotes State - Dark Mode |
|---|---|---|---|
|Simulator Screen Shot - iPhone 11 Pro - 2020-10-01 at 14 25 15| Simulator Screen Shot - iPhone 11 Pro - 2020-10-01 at 17 07 01|Simulator Screen Shot - iPhone 11 Pro - 2020-10-01 at 14 25 23|Simulator Screen Shot - iPhone 11 Pro - 2020-10-01 at 17 07 04|

To view onboarding in action:
Go To Project Navigator > Footnote > Target (Footnote) > Change Version to 1.03.1 etc and run the app.

**Known Issue**:

I created an additional sheet modifier for viewing the onboarding. Since it was causing problems with AddQuoteView Sheet ie: AddQuoteView was not opening.

**Workaround**:
I had commented the enum which change the modal views. Instead added a sheet modifier to the button as workaround.

I have one feedback on the codebase, ie: Readability can be improved.
Waiting for the feedbacks and suggestions.

### CODE REVIEW

**Comment by cambardell** [comment]
Thanks @rajhraval1, looks great. Will review later today.

**Comment by cambardell** [comment]
I'm not sure the onboarding screen needs to be shown every time there's a new app version. For example, if there's a simple bug fix update, it might be annoying to have to go through onboarding. What are your thoughts @rajhraval1?

**Comment by cambardell** [comment]
I think ideally, the user only sees the onboarding screen once on initial download, and never again. I think the simplest way to do this is just save a boolean to NSUserDefaults the first time the user launches the app, I don't think saving the app version is necessary.

**Comment by cambardell** [comment]
System apps for the most part only onboard on first open. I think that's best, especially since the core feature set of this app is unlikely to radically change.

**Comment by rajhraval1** [comment]
OK, Then. It's a One-Time Onboarding, on my for the submit a change in the PR!

**Comment by rajhraval1** [comment]
One-time onboarding is done. It will happen only the first time, when the app is downloaded.

@cambardell should I create a new PR? I see some conflict issues, here.

**Comment by cambardell** [comment]
I think you're good @rajhraval1, the conflicts don't seem to be a big deal. I'll review today.

**Comment by rajhraval1** [comment]
Do let me know. I want to volunteer for new issues too.

**Pull request merged**
