### PR TITLE
Revamped Search UX

### LINKED ISSUE #62: Replacing present search bar by a native, pull down to search style search bar
Hi, I found a way to implement a native search bar in SwiftUI which hides the search bar until the view is pulled down, mimicking the behavior found commonly in iOS like in spotlight and the settings app.
Should be a nice replacement, let me know what you think.

### LINKED ISSUE #63: Improve search UI
The search UI is a little bit weird.
Animations and filtering should be smoother.

### PR DESCRIPTION
**Pull request by JapneetSingh5**
Refactored Content View and improved search experience.
Closes #62 
Closes #63 

<a href="url"></a>

<a href="url"></a>

<a href="url"></a>

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
@cambardell I have refactored ContentView a bit, used initializer overloading to accommodate both the filtered and unfiltered view in the FilteredList view itself.

**Comment by Drag0ndust** [comment]
Oh, you already worked on it?

Wanted to do that and waited for the assignement of @cambardell

**Comment by cambardell** [comment]
Sorry everyone, the confusion here is my fault. I was busy for a few days and didn't properly keep track of who was doing what. @JapneetSingh5 I would ask in the future that you wait until I assign you the issue to do any work on it, as stated in the contributing guidelines. @Drag0ndust That's my mistake, is there anything else you would like to work on? I'm sure there are further improvements to be made to search, or you can pick another issue/open one yourself.

**Comment by Drag0ndust** [comment]
@cambardell: Most of the issues are already assigned. Do you have something special in mind?

**Comment by cambardell** [comment]
@Drag0ndust if you're interested in #22 or #15, either of those would be great. otherwise feel free to make a feature request and work on it yourself

**Comment by JapneetSingh5** [comment]
I am sorry @cambardell @Drag0ndust, I had worked a bit on this before adding an issue, forgot that you hadn't assigned it yet. Will make sure I clear things up before working on something in the future. Really sorry for this.

**Comment by JapneetSingh5** [comment]
@cambardell Are the merge conflicts creating problems?

**Comment by JapneetSingh5** [comment]
@cambardell any updates?

**Comment by cambardell** [comment]
Sorry @JapneetSingh5, I started a new job so I've been falling behind. Catching up now. There seems to be a large amount to merge conflicts here, would you mind taking a look?

**Pull request closed without merging**
