### PR TITLE
Adds ShareSheet - ability to share Image directly to other apps

### LINKED ISSUE #18: Export to social media.
Currently, quotes can be exported and saved to the photo library. This feature would be more useful if it supported export to social media, mostly likely Twitter and Instagram.

### LINKED ISSUE #33: Share View Layout Issue
The current version of Footnote produces a layout issue in iPhone SE (1st Generation).

When the users clicks on "Share Quote", a sheet appears to customise the Footnote (Quote).
The submit button is not properly be seen on the screen.

iPhone SE

Hope, it gets resolved.

### PR DESCRIPTION
**Pull request by JapneetSingh5**
Simulator Screen Shot - iPhone 11 - 2020-10-02 at 19 29 34
Simulator Screen Shot - iPhone 11 - 2020-10-02 at 19 29 53

closes #18 
closes #33

### CODE REVIEW

**Comment by JapneetSingh5** [comment]
Hi @cambardell, I have implemented the Share Sheet by wrapping UIViewActivityController.

**Comment by cambardell** [comment]
Awesome work @JapneetSingh5, will merge tonight.

**Comment by JapneetSingh5** [comment]
Thankyou @cambardell, I also had a doubt. I had trouble trying to run the app on my iPhone from Xcode, is it because of the project being signed by your Developer account? Is there a workaround? This might also be because my phone is on 14.2 beta, just wanted to know if this is always the case.

**Comment by cambardell** [comment]
Yeah it probably has something to do with the developer account. I haven't figured out if there's a way to configure the project so that everyone can run it. It should be fine in the simulator though.

**Comment by cambardell** [comment]
Thanks so much @JapneetSingh5, merging!

**Pull request merged**
