### PR TITLE
change Footnote2 to Footnote

### PR DESCRIPTION
**Pull request by VPhung24**
Per issue #8, changing Footnote2 to Footnote

### CODE REVIEW

**Comment by VPhung24** [comment]
The second commit should not be in this branch. Anyways, I personally have strong feelings against lower left corner buttons (android style apps imo). a Navigation button seems like the best way to add. Also added the contributions, but feel free to delete.

**Comment by cambardell** [comment]
Thanks @VPhung24! A couple things: 
* Please comment on the specific issues you wish to address so I can assign them to you before submitting a PR, as stated in the contributing guide. That way we can avoid multiple people working on the same issue. 
* Based on this, if you want to change the navigation button, please create an issue with your proposed change, I'll assign it to you, and then you can create a new PR associated with that issue. 
* I did the renaming myself this morning, so that's not necessary anymore. 
* Someone else already claimed the contributors screen, so I'm leaving it to them. Feel free to comment on that issue if you have input.

**Comment by cambardell** [comment]
Closing for now based on the above, but we can keep discussing this here

**Comment by cambardell** [comment]
Also @VPhung24 if you're participating in Hacktoberfest, your PRs won't be counted until October 1st. It's up to you but if you want it to count to your total you can submit the navigation button changes in a couple days.

**Pull request closed without merging**
